base_lr: 0.01
batch_size: 256
config: config/st_gcn/kinetics-skeleton/test.yaml
device: 0
eval_interval: 5
feeder: st_gcn.feeder.Feeder_kinetics
ignore_weights: []
log_interval: 100
model: st_gcn.net.ST_GCN
model_args:
  channel: 3
  dropout: 0
  graph: st_gcn.graph.Kinetics
  graph_args:
    labeling_mode: spatial
  mask_learning: true
  num_class: 400
  num_person: 2
  num_point: 18
  use_data_bn: true
  window_size: 150
nesterov: false
num_epoch: 80
num_worker: 128
optimizer: SGD
phase: test
print_log: true
save_interval: 10
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 64
test_feeder_args:
  data_path: ./data/kinetics-skeleton/kinetics_val
  label_path: ./data/kinetics-skeleton/kinetics_val_label.json
  mode: test
  window_size: 150
train_feeder_args: {}
weight_decay: 0.0005
weights: ./model/kinetics-st_gcn.pt
work_dir: ./work_dir/temp
